@echo off
rem v2.10: per-build version auto-increment.
rem Runs as the MiniSys project's PreBuildEvent (see MiniSys.vcxproj):
rem   - bumps MiniSys/src/res/build_number.txt (tracked in git)
rem   - (re)generates MiniSys/src/res/version.h (gitignored, generated)
rem version.h is the single source of truth consumed by MainWindow.cpp
rem (title bar + About) and MiniSys.rc (FileVersion/ProductVersion).
setlocal enableextensions

set "NUMFILE=%~dp0..\MiniSys\src\res\build_number.txt"
set "VH=%~dp0..\MiniSys\src\res\version.h"

set N=0
if exist "%NUMFILE%" set /p N=<"%NUMFILE%"
if not defined N set N=0
rem only numeric values survive this check; anything else resets to 0
set /a N+=1 2>nul || set N=1
>%NUMFILE% echo %N%

> "%VH%" echo #pragma once
>>"%VH%" echo // GENERATED by tools/incr_build.bat -- do not edit by hand.
>>"%VH%" echo #define MINISYS_VERSION_MAJOR 2
>>"%VH%" echo #define MINISYS_VERSION_MINOR 10
>>"%VH%" echo #define MINISYS_VERSION_BUILD %N%
>>"%VH%" echo #define MINISYS_VERSION_RC 2,10,%N%,0
>>"%VH%" echo #define MINISYS_VERSION_STR "2.10.%N%.0"
>>"%VH%" echo #define MINISYS_VERSION_TITLE L"v2.10 build %N%"

endlocal
